<?php
/**
 * @file
 * Code for the ELX User Dashboard feature.
 */

include_once 'elx_user_dashboard.features.inc';

/**
 * Implements hook_views_pre_execute().
 */
function elx_user_dashboard_views_pre_execute(&$view) {
  if ($view->name == 'levels_quizz_progress' && $view->current_display == 'completed_count') {
    $view->get_total_rows = TRUE;
  }
}

/**
 * Implements hook_views_pre_render().
 */
function elx_user_dashboard_views_pre_render(&$view) {
  if (!empty($view->result) && $view->name == 'levels_quizz_progress') {
    switch ($view->current_display) {
      case 'completed_count':
        $row = array_shift($view->result);
        $row->taxonomy_term_data_node_tid = $view->total_rows;
        $view->result = array($row);
        break;

      case 'closest_completion':
        $view->result = array(array_reduce($view->result, '_elx_user_dashboard_closest_completion'));
        break;
    }
  }
}

function _elx_user_dashboard_closest_completion($last, $current) {
  if (isset($last)) {
    $last_percent = $last->flagging_node_uid / $last->nid;
    $current_percent = $current->flagging_node_uid / $current->nid;
    return $last_percent > $current_percent ? $last : $current;
  }
  else {
    return $current;
  }
}
