<?php
/**
 * @file
 * learner_pathways.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function learner_pathways_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Beautiful Skin for Life',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '0d1a41e8-b4c7-4a2d-b973-78b6b2c2f381',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'learning_category',
  );
  $terms[] = array(
    'name' => 'Advanced Night Repair',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '194b5041-4e6a-4dfc-a6ae-ad4f3c158722',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'learning_category',
  );
  $terms[] = array(
    'name' => 'Spring Preview',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '433eb252-807e-4470-8135-cd9278b54291',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'learning_category',
  );
  $terms[] = array(
    'name' => 'GMTC',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '45798643-68d2-46c8-98ce-cb82a5ce5d07',
    'language' => 'en',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'learning_category',
  );
  $terms[] = array(
    'name' => 'Fall Preview',
    'description' => '<p>Fall Preview 2016</p>',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '6b7ae0c2-3355-4b06-9ced-b73834e32f14',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'learning_category',
  );
  $terms[] = array(
    'name' => 'Advanced Night Repair 2',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8c526acc-48f7-47b1-a4c2-e91ff00c160e',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'learning_category',
  );
  $terms[] = array(
    'name' => 'New Dimension 2',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8f0f849b-6d9c-4bc9-9bd9-c9292d5b63ad',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'learning_category',
  );
  $terms[] = array(
    'name' => 'Re-Nutriv',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9900e7bb-9c18-4cbd-a0f6-2123ef2a04fd',
    'language' => 'enus',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'learning_category',
  );
  $terms[] = array(
    'name' => 'Holiday',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9b2fed0e-b181-4493-a001-65176f3de310',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'learning_category',
  );
  $terms[] = array(
    'name' => 'New Dimension',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ac916cd3-e9d9-4d6d-8b85-44f7d4d657c5',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'learning_category',
  );
  $terms[] = array(
    'name' => 'Beautiful Start',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'bb78eea6-7a77-46f2-b5c6-be7ceea6ac47',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'learning_category',
  );
  return $terms;
}
