<?php
/**
 * @file
 * Code for the ELX Guest URL feature.
 */

include_once 'elx_guest_url.features.inc';

/**
 * Implements hook_form_FORM_ID_alter()
 * Add option to register through guest URLs only in Account Settings page
 */
function elx_guest_url_form_user_admin_settings_alter(&$form, &$form_state, $form_id)
{
    $form['registration_cancellation']['user_register']['#options']['invite_only'] = t('New user registration through Guest URLs only.');
}

/**
 * Implements hook_menu().
 * To allow user account registration through guest URLs
 */
function elx_guest_url_menu() {
    $items['signup'] = array(
      'page callback' => '_guest_account_creation',
	  'access callback' => TRUE,
	  'type' => MENU_CALLBACK,
    );
    return $items;
}

/**
 * Implements hook_menu_alter().
 * Grant permission to register without admin approval if "New user registration through Guest URLs only." option is selected in User Account settings page
 */
function elx_guest_url_menu_alter(&$items) {
  $items['user/register']['access callback'] = '_registration_invite_user_register_access';
}

/**
 * User defined callback function to create guest user account by redirecting to user/register along with door, account name, etc. details
 */
function _guest_account_creation()
{
	$options = array('query' => drupal_get_query_parameters());
	drupal_goto('user/register', $options);
}

/**
 * User defined callback function which decides whether user/register?<query parameters> is accessible or not
 */
function _registration_invite_user_register_access() {
  if (array_diff(array(
    'account',
    'door',
    'country',
    'region',
    'market',
  ), array_keys(drupal_get_query_parameters()))) {
    return user_register_access();
  }
  else {
    // @todo: Check that the parameters are valid.
    return user_is_anonymous();
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 * Pre-populate fields depending on the query parameters
 */
function elx_guest_url_form_user_register_form_alter(&$form, &$form_state, $form_id)
{
	$query = drupal_get_query_parameters();
	
	if(isset($query['account']))$form['field_account_name'][LANGUAGE_NONE][0]['value']['#default_value'] = $query['account'];
	if(isset($query['door']))$form['field_door'][LANGUAGE_NONE][0]['value']['#default_value'] = $query['door'];
	if(isset($query['country']))$form['field_country'][LANGUAGE_NONE]['#default_value'][0] = $query['country'];
	if(isset($query['region']))$form['field_region_list'][LANGUAGE_NONE]['#default_value'][0] = $query['region'];
	if(isset($query['market']))$form['field_market_name'][LANGUAGE_NONE]['#default_value'][0] = $query['market'];
	
	//Hide all optional fields from User Registration page since only guests access user/register & they don't need to enter these values
	$optionalFields = array('field_account_name','field_door','field_country','field_region_list','field_market_name','field_employer_number','field_hire_date','field_counter_manager','field_education_manager_executiv','field_account_field_executive','field_field_sales_director_regio','field_regional_vice_president','field_general_manager_brand_mana','field_market_administrator','field_city','field_state','field_level','field_rank','field_modified_date','field_last_access_date');
	foreach($optionalFields as $optionalField)
		$form[$optionalField]['#access'] = 0;
}