<?php
/**
 * @file
 * Code for the ELX Interactive Content Feature feature.
 */

include_once 'elx_interactive_content_feature.features.inc';

/**
 * Alter a library's semantics
 *
 * Included by SUPRIYA RAJGOPAL on 27Jul16 to make Click to Reveal H5P library usable in Course Presentation H5P content type
 * Borrowed from https://www.drupal.org/node/2772799 and http://cgit.drupalcode.org/h5p/tree/h5p.api.php
 *
 * May be used to add more fields to a library, change a widget, add more allowed tags for
 * a textfield etc
 *
 * @param array $semantics
 * A libraries definition of the data the library uses
 * @param string $machine_name
 * The libraries machine name
 * @param int $major_version
 * Major version for the library
 * @param int $minor_version
 * Minor version fot the library
 */
function elx_interactive_content_feature_h5p_semantics_alter(&$semantics, $machine_name, $major_version, $minor_version)
{
  //Make Click to Reveal library usable in Course Presentation
  if($machine_name == 'H5P.CoursePresentation')
  {
	$slides = $semantics[0]->fields[0];
	$elements = $slides->field->fields[0];
	$action = $elements->field->fields[4];
	$action->options[] = "H5P.ClickToReveal 1.0";
	
	$slides = $semantics[0]->fields[0];
	$elements = $slides->field->fields[0];
	$action = $elements->field->fields[4];
	$action->options[] = "H5P.QuestionSet 1.8";
	
	$slides = $semantics[0]->fields[0];
	$elements = $slides->field->fields[0];
	$action = $elements->field->fields[4];
	$action->options[] = "H5P.ImageHotspots 1.3";
  }
  
  //Allow HTML in Dialog Cards text fields
  if($machine_name == 'H5P.Dialogcards')
  {
	$dialog_front = $semantics[2]->field->fields[0];
	$dialog_back = $semantics[2]->field->fields[1];
	$dialog_front->widget = $dialog_back->widget = 'html'; //Allow HTML
	$dialog_front->tags = $dialog_back->tags = array('p','br','strong','em','ul','li','ol','dl','dt','sup','u'); //Allowed tags
	$dialog_back->optional = true; //Make text at the back of Dialog card optional
  }

  //Allow table in Advanced Text
  if($machine_name == 'H5P.AdvancedText')
	array_push($semantics[0]->tags,'table','tr','td','thead','tbody','tfoot');
  
  //Make 'Correct Feedback' & new 'Incorrect Feedback' settings per Drag&Drop question instead of common setting
  if($machine_name == 'H5P.DragQuestion')
  {
	//Alter existing 'Feedback text' setting
	$semantics[3]->label = t('Correct feedback text');
	$semantics[3]->common = false; //To show this for every Drag & Drop question inside a question set instead of common to all drag-and-drop questions
	
	//Create new 'Incorrect feedback text' setting
	$incorrectFeedbackSetting = new stdClass();
	$incorrectFeedbackSetting->label = t('Incorrect feedback text');
	$incorrectFeedbackSetting->name = 'incorrect_feedback';
	$incorrectFeedbackSetting->type = 'text';
	$incorrectFeedbackSetting->default = t('Sorry, this answer is incorrect');
	$incorrectFeedbackSetting->description = t('Feedback text when incorrect answer is provided, variables available: @score and @total.');
	$incorrectFeedbackSetting->common = false;
	/*Insert this new setting next to 'Correct feedback text' setting. Borrowed from http://stackoverflow.com/questions/3797239/insert-new-item-in-array-on-any-position-in-php*/
	array_splice($semantics,4,0,array($incorrectFeedbackSetting));
  }
}

/**
 * Alter Javascript functionalities of H5P libraries
 * 
 * Included by SUPRIYA RAJGOPAL on 27Aug16
 * Borrowed from http://cgit.drupalcode.org/h5p/tree/h5p.api.php
 
 * @param array $scripts
 *  Array of objects with properties path and version. Version is on the form
 *  ?ver=1.0.2 and is used as a cache buster
 * @param array $libraries
 *  Array of libraries indexed by the library's machineName and with an array
 *  as value. The value has the properties majorVersion and minorVersion
 * @param string $mode
 *  What mode are we in? Possible values are "editor", "div", "iframe" and "external"
 */
function elx_interactive_content_feature_h5p_scripts_alter(&$scripts, $libraries, $mode) {
  if(isset($libraries['H5P.DragQuestion'])) {
    $scripts[] = (object) array(
      'path' => drupal_get_path('module', 'elx_interactive_content_feature') . '/js/h5p-dragdrop-question.js', //Custom JS file path
    );
  }
}
