<?php

//require_once 'includes/password.inc';
//require_once 'sites/all/modules/contrib/aes/aes.module';
//require_once 'includes/database/prefetch.inc';


function elx_utility_node_validate($node, $form, &$form_state) {
  // dpm($node);
  // if ($node->type=='history' || $node->type=='teaser') {
  //   if (strlen($node->field_link['und'][0]['url']) && $node->field_video_upload['und'][0]['fid']) {
  //     form_set_error('field', t('You may either use a link or a video, not both.'));
  //   }
  //   elseif (!(strlen($node->field_link['und'][0]['url']) || $node->field_video_upload['und'][0]['fid'])) {
  //     form_set_error('field', t('You must choose either a link or a video (but not both).'));
  //   }
  // }
}


/**
 * Implements hook_preprocess_html.
 */
function elx_utility_preprocess_html(&$variables) {
// Add conditional stylesheets for admin pages on admin theme.
  global $user;
  if ($user->uid) {
    // reference your current admin theme
    $theme_path = drupal_get_path('theme', 'seven');
    // reference your own stylesheet
    drupal_add_css(drupal_get_path('module', 'elx_utility')
    . '/admin.css', array('weight' => CSS_THEME));
    drupal_add_js(drupal_get_path('module', 'elx_utility')
    . '/admin.js');
    drupal_add_js(drupal_get_path('module', 'elx_utility')
    . '/jquery.alphanum.js');
    
  }
}

/**
 * Random pass generator.
 */
function randomPassword() {
  $alphabet = "abcdefghijkmnopqrstuwxyzABCDEFGHJKMNPQRSTUWXYZ23456789";
  $pass = array(); //remember to declare $pass as an array
  $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
  for ($i = 0; $i < 8; $i++) {
    $n = rand(0, $alphaLength);
    $pass[] = $alphabet[$n];
  }
  return implode($pass); //turn the array into a string
}

/**
 * Implements hook_feeds_after_save().
 * Auto-generate user password on user feed import
 */
function elx_utility_feeds_after_save(FeedsSource $source, $entity, $item, $entity_id) {
  if (isset($entity->pass) && $entity->pass == '') {
    require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');
    $password = randomPassword();
    $encrypted_data = aes_encrypt($password);
    watchdog('elx_utility_feeds_after_save', 'New user ' . $entity->uid . ' new password.');
    $entity->pass = $password;
    db_insert('aes_passwords')
      ->fields(array(
        'uid' => $entity->uid,
        'pass' => $encrypted_data,
      ))
      ->execute();
    $pass = user_hash_password($password);
    db_update('users')
      ->fields(array('pass' => $pass))
      ->where("uid = :uid", array(
        ':uid' => $entity->uid,
      ))
      ->execute();
    $account = user_load($entity->uid);
    drupal_mail('user', 'register_admin_created', $account->mail, $entity->language, array('account' => $account), variable_get('site_mail', 'noreply-myelx@estee.com'));
  }
}

/**
 * Implements hook_clone_node_alter().
 */
function elx_utility_clone_node_alter(&$node, $context) {
  $lang = $node->language;
  // Empty manifest reference
  if (isset($node->field_manifest[$lang][0]['target_id'])) {
    $node->field_manifest[$lang][0]['target_id'] = '';
  }
}

/**
 * Implements hook_feeds_after_parse().
 */
function elx_utility_feeds_after_parse(FeedsSource $source, FeedsParserResult $result) {
  // add space to all field_keys for data_xls import
  // some field_keys have spaces after parsing and can't alter mapping directly
  if ($source->importer->id == 'data_xls') {
    foreach ($result->items as $item_key => $item) {
      foreach($item as $field_key => $field_val) {
        $result->items[$item_key][$field_key . ' '] = $field_val;
      }
    }
  }
}

/**
 * Implements hook_entity_info_alter().
 * Created by SUPRIYA RAJGOPAL on 21Jul16 to create a view mode for nodes so that they can be displayed in a modal using Ctools modal
 * Borrowed from http://www.wunderkraut.com/blog/drupal-7-custom-node-view-modes/2010-12-20
 */
function elx_utility_entity_info_alter(&$entity_info)
{
  $entity_info['node']['view modes']['modal'] = array(
    'label' => t('Modal'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_menu().
 * Created by SUPRIYA RAJGOPAL on 21Jul16 to define a path which renders product details in a modal
 * !Note: The click to this path should be AJAX enabled by adding 'use-ajax' class
 * Borrowed from https://www.drupion.com/blog/10-steps-creating-ctools-modal-window-drupal-7
 */
function elx_utility_menu()
{
  $items['modal/%ctools_js/%'] = array(
      'title' => 'ELX Custom Modal',
      'page arguments' => array(1,2), //Pass whether to use AJAX or JS and the nid
      'page callback' => '_elx_custom_modal', //User defined function called when the link is clicked
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM, //Internal path menu, not a menu tab
  );
 
  $items['modal/%ctools_js/flags/%'] = array(
      'title' => 'Product Details Modal',
      'page arguments' => array(1,3), //Pass whether to use AJAX or JS and the machine name of the flag
      'page callback' => '_elx_badges_modal', //User defined function called when the link is clicked
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM, //Internal path menu, not a menu tab
  );
  return $items;
}

function _elx_custom_modal($js = NULL, $nid = NULL)
{
  if($nid == NULL)
   return 'No content to display.';
 
  //Include ctools if path contains 'nojs' to work, else render page normally
  if($js)
  {
    ctools_include('modal');
    ctools_include('ajax');
	  ctools_modal_add_js(); //Default CTools JS. This is a must if custom javascript is not available.
    drupal_add_js(array(
        'elx-tools' => array(
          'modalSize' => array(
            'type' => 'scale',
            'width' => .6,
            'height' => .8,
            'contentRight' => 5,
            'contentBottom' => 20,
          ),
          'animation' => 'slideDown',
          'closeText' => t(''),
          'closeImage' => t(''),
          //'closeImage' => base_path() . path_to_theme() . '',
        ),
      ), 'setting');
      
    drupal_add_js(array(
        'product-library' => array(
          'modalSize' => array(
            'type' => 'scale',
            'width' => 1,
            'height' => 1,
            'contentRight' => 5,
            'contentBottom' => 20,
          ),
          'animation' => 'slideDown',
          'closeText' => t(''),
          'closeImage' => t(''),
          //'closeImage' => base_path() . path_to_theme() . '',
        ),
      ), 'setting');
      
    drupal_add_js(array(
        'search-product-library' => array(
          'modalSize' => array(
            'type' => 'scale',
            'width' => 1,
            'height' => 1,
            'contentRight' => 5,
            'contentBottom' => 20,
          ),
          'animation' => 'slideDown',
          'closeText' => t(''),
          'closeImage' => t(''),
          //'closeImage' => base_path() . path_to_theme() . '',
        ),
      ), 'setting');

      drupal_add_js(array(
          'levels' => array(
            'modalSize' => array(
              'type' => 'scale',
              'width' => 1,
              'height' => 1,
              'addHeight' => 80, // this needs to match the css height for div.modal-header or it acts buggy
              'contentRight' => 5,
              'contentBottom' => 0,
            ),
            'modalClass' => 'default',
            'animation' => 'slideDown',
            'closeText' => t(''),
            'closeImage' => t(''),
            //'closeImage' => base_path() . path_to_theme() . '',
          ),
        ), 'setting');
    
  }
  
  //Load the node object
  $node = node_load($nid);
  
  //Render content in 'Modal' view mode
  $nodeContent = node_view($node, 'modal', NULL); //To prevent strict warning that only variables can be passed by reference
  $contents = render($nodeContent);
  $integration = h5p_add_files_and_settings(NULL, NULL);
  if ($integration) {
    drupal_add_js(array('H5PIntegration' => $integration), 'setting');
  }
  return ctools_modal_render($node->title, $contents) ;
}

/**
 * User defined page callback created by SUPRIYA RAJGOPAL on 2Aug16 to show badge title in a modal
 * Borrowed from https://www.drupion.com/blog/10-steps-creating-ctools-modal-window-drupal-7
 *
 * @param $js
 *   boolean CTools determination whether the user's browser is javascript enabled. 
 * @param $flag_name
 *   string The machine name of flag passed as an argument from the hook_menu() path
 * @return
 *   string The flag title in a modal window
 */
function _elx_badges_modal($js = NULL, $flag_name = NULL)
{
  global $user;
  if($flag_name == NULL)
   return 'No content to display.';
   
  //Include ctools iff path contains 'nojs' to work, else render page normally
  if($js)
  {
    ctools_include('modal');
    ctools_include('ajax');
	ctools_modal_add_js(); //Default CTools JS. This is a must if custom javascript is not available.
  }
  
  $flag = flag_load($flag_name); //Load the flag object
  $is_flagged = $flag->is_flagged($user->uid);//is the current user flagged?
  
  //Form the modal content
  $rendered_title = (isset($flag->title) && $flag->title != '')?$flag->title:'';
  $rendered_description = (isset($flag->badge_description) && $flag->badge_description != '')?$flag->badge_description:'';
  $rendered_undescription = (isset($flag->badge_unearned_description) && $flag->badge_unearned_description != '')?$flag->badge_unearned_description:'';
  //$image = (isset($flag->badge_image) && $flag->badge_image != 0)?file_load($flag->badge_image):FALSE;
  //$rendered_img = ($image)?'Image: '.render(theme_image_style(array('style_name' => 'thumbnail','path' => $image->uri))):'';

  if ($is_flagged) {
    $output = $rendered_description;
  } else {
    $output = $rendered_undescription;
  }

  return ctools_modal_render($rendered_title.":".$output,$output); //Render content in 'Modal' view mode
  //return ctools_modal_render($flag->title,$output); //Render content in 'Modal' view mode
}

function elx_utility_init()
{
	global $user;
	if(user_is_logged_in() && _userNotBelongsToSpecificMarkets() && !in_array('administrator', array_values($user->roles)))
	{
		drupal_set_message(t('@errorMsg',array('@errorMsg' => errorMsg($user->language))));
		drupal_access_denied();
		module_invoke_all('exit');
		drupal_exit();
	}
	
	if(!user_is_logged_in() && arg(0) == 'user' && empty(arg(1)))
	 drupal_goto('user/login');
}

/**
 * Helper function that returns the 'site not accessible' message in the desired language
 * Borrowed from https://github.com/MasterDoublePrime/elx-varnish/blob/master/var/www/errors/503_coming_soon.html
 */
function errorMsg($language)
{
  $langError = '';
  
  // [mo] for Moldavian has been withdrawn, recommending [ro] also for Moldavian
  if ($language === 'mo') {
    $language = 'ro';
  }
  // nn and no also Norwegian
  if ($language === 'nn' || $language === 'no') {
    $language = 'nb';
  }
  // Chinese -> Traditional Chinese (FF only sends 'zh').
  if ($language === 'zh') {
    $language = 'zh-Hant';
  }
  // zh-CN is much more common code for Simplified Chinese.
  if ($language === 'zh-CN') {
    $language = 'zh-Hans';
  }
  // zh-TW is much more common code for Traditional Chinese.
  if ($language == 'zh-TW') {
    $language = 'zh-Hant';
  }
  // Default to english.
  if (!$language) {
    $language = 'en';
  }
  //Spanish     
  if ($language === 'es') {
  	$langError = '¡ELX está en mantenimiento en este momento, haciendo una serie de mejoras en el sistema. Por favor regresa el 10 de octobre de 2016 para experimentar mejoras emocionantes y nuevas características. También encontrarás nuevo contenido para aprender. No te lo pierdas. Te vemos pronto!';
  }
  //Romanian     
  else if ($language === 'ro') {
  	$langError = 'ELX este in prezent in modul de intretinere. Te rugam sa verifici din nou in curand - ne cerem scuze pentru orice inconvenient.';
  }
  //Turkish     
  else if ($language === 'tr') {
  	$langError = 'ELX , yüklenecek yeni içerikler nedeniyle şu an bakım çalışmasındadır. ELX’in  yepyeni ve heyecan verici yüzüyle ve özellikleriyle tanışmak için sizi, 10/10/2016 tarihinde, ELX’e giriş yapmaya davet ediyoruz. Yeni lansmanlarımız ve içeriklerine de ulaşabileceğiniz bu muhteşem deneyimi sakın kaçırmayın. Görüşmek üzere.';
  }
  //Hungarian     
  else if ($language === 'hu') {
  	$langError = 'Az ELX jelenleg karbantartás alatt áll a frissítések feltöltése céljából. Látogass vissza az oldalra : 10/10/2016 (hónap/nap/év) –tól és fedezd fel az újdonságokat, fejlesztéseket, legfrisebb tartalmakat. Ne maradj le! Visszavárunk!';
  }
  //Russian     
  else if ($language === 'ru') {
  	$langError = 'Программа временно недоступна, так как выполняется ряд обновлений. Вы сможете вернуться в ELX после 10.10.2016, чтобы узнать об изменениях и улучшениях функций программы. Так же будет доступен для изучения новый контент. Не пропустите! До новых встреч!';
  }
  //Latvian     
  else if ($language === 'lv') {
  	$langError = "ELX pašlaik tiek veikta apkope, vietnes atjauninājumiem. Lūdzu, dodieties 10/10/2016 (dd / mm / gggg), jūs redzēsiet mazliet jauna pieredze uzlabotu sistēmu un jaunas funkcijas. Mēs arī turėseme jaunu saturu pieejami, lai jūs varētu mācīties. Nepalaidiet garām. Uz \ndrīzu tikšanos!";
  }
  //Lithuanian     
  else if ($language === 'lt') {
  	$langError = 'Elx šiuo metu vyksta techninės priežiūros darbai   ,  svetaines atnaujinimai. Prašome grįžti   10/10/2016 (DD / MM / YYYY) pamatysite šiek tiek naujos patirties patobulinta sistema ir naujos funkcijos. Mes taip pat turėseme naują turinį prieinami jums išmokti. Nepraleiskite. Iki greito pasimatymo!';
  }
  //Finnish     
  else if ($language === 'fi') {
  	$langError = "ELX on tällä hetkellä huollossa,  huollon jälkeen luvassa useita parannuksia ja sisältöä sivustolle . Tervetuloa takaisin 10.10.2016. \nMeillä on myös siinä vaiheessa uutta materiaalia opittavaksi. Älä missaa uutuuksia. Nähdään pian!";
  }
  //Polish     
  else if ($language === 'pl') {
  	$langError = 'Trwa przerwa techniczna na stronie ELX w celu poprawienia jej jakości. Zapraszamy ponownie 10/10/2016 (mm/dd/rrrr) do odkrywania lepszego serwisu i nowych funkcji. Powrócimy również z nowymi informacjami do czytania. Nie przegap nowości! Do zobaczenia wkrótce!';
  }
  //Norwegian     
  else if ($language === 'nb') {
  	$langError = 'ELX er fortiden i en oppgraderingsfase, og gjennomfører en mengde oppgraderinger. Vennligst kom tilbake 10/10/2016 (mm/dd/yyyy) for å oppleve spennende system forbedringer og nye opplevelser. Vi vil også ha nytt innhold tilgjengelig for deg slik at du kan lære enda mer. Ikke gå glipp av dette. Vi sees snart!';
  }
  //Swedish     
  else if ($language === 'sv') {
  	$langError = 'ELX är utför just nu en rad olika uppdateringar på webbplatsen. Vänligen återkom 2016/10/10 (mm / dd / åååå) för att uppleva några spännande systemförbättringar och nya funktioner. Vi kommer också att lansera ett helt nytt innehåll som blir tillgängligt för dig så att du kan lära dig ännu mer. Missa det inte. Vi ses snart!';
  }
  //Danish     
  else if ($language === 'da') {
  	$langError = 'ELX er lige nu under opdatering. Kom venligst tilbage d. 10/10/2016 for at opleve nogle spændende systemforbedringer og nye funktioner. Der vil også være helt nyt indhold tilgængeligt så du kan lære endnu mere. Gå ikke glip af det. Vi ses snart!';
  }
  //Arabic     
  else if ($language === 'ar') {
  	$langError = 'ELX حاليا في وضع الصيانة و إداء سلسلة من التحسيينات للموقع. يرجى العودة في 10/10/2016 لتجربة بعض التحسينات المثيرة للنظام و الميزات الجديدة. سيكون لدينا محتوى جديد متاح لك للتعلم ايضاً. لا تفوت الفرصة. سوف نراك قريبا!';
  }
  //Italian     
  else if ($language === 'it') {
  	$langError = 'ELX è in fase di aggiornamento. Ritorna su ELX il 10/10/2016 per scoprire miglioramenti e nuove funzionalità. Ci saranno anche nuovi contenuti e aggiornamenti. Non mancare ti aspettiamo presto su ELX!';
  }
  //Hebrew
  else if ($language === 'he') {
    $langError = 'ELX אינו פעיל כעת בשל ביצוע סדרת שדרוגים באתר. אנא חזרו אלינו בתאריך 10/10/2016 כדי להתנסות במערכת משופרת, מאפיינים חדשים ותוכן לימודי חדש. אל תפספסו. נתראה בקרוב!';
  }
  //Greek     
  else if ($language === 'el') {
  	$langError = "Το ΕLX βρίσκεται υπό συντήρηση, καθώς διενεργούνται εργασίες αναβάθμισης στην ιστοσελίδα.\n\nΜπορείτε να επανέλθετε στην ιστοσελίδα στις 10/10/2016 για να ζήσετε τη συναρπαστική εμπειρία της εξέλιξης του συστήματος, με τα νέα του χαρακτηριστικά. Επίσης θα έχουμε στη διάθεσή σας νέες πληροφορίες και περιεχόμενα για να διευρύνετε τις γνώσεις σας. Μην ξεχάσετε να μας επισκεφθείτε. Θα είμαστε σύντομα κοντά σας !";
  }
  //German     
  else if ($language === 'de') {
  	$langError = "ELX wird momentan für Euch bearbeitet. \nAb 10.10.2016 begrüßen wir Euch wieder mit viel Neuem! Lasst Euch überraschen und freut Euch auf die attraktiven Inhalte. \nBitte notiert Euch im Kalender, dass Ihr Euch am 15.09. wieder einloggt.  Bis dahin!";
  }
  //Czech     
  else if ($language === 'cs') {
  	$langError = 'ELX je v současné době v režimu údržby. Provádíme aktualizaci. Prosím vraťte se na stránky 10.10. 2016 a objevujte mnoho nových vylepšení a funkcí. Těšit se můžete i na nový obsah. Nenechte se to ujít. Brzy na shledanou!';
  }
  //Dutch     
  else if ($language === 'nl') {
  	$langError = 'Wegens onderhoudswerkzaamheden is de ELX-website tijdelijk niet beschikbaar. We verwelkomen je graag terug op 10 october 2016 met enkele systeemverbeteringen en nieuwe toepassingen. Je zal ook nieuwe inhoud kunnen ontdekken die je niet mag missen. Graag tot snel!';
  }
  //Thai     
  else if ($language === 'th') {
  	$langError = "ขณะนี้ ELX อยู่ในช่วงปรับปรุง เพื่อเพิ่มประสิทธิภาพการเข้าใช้งานในเว๊ปไซด์ให้ดียิ่งขึ้น จึงขอให้คุณกลับมาเข้าใช้งานอีกครั้งใน วันที่ 10 ตุลาคม 2016 เป็นต้นไป\": \"ซึ่งคุณจะได้สัมผัสระบบใหม่และคุณสมบัติการใช้งานที่ดียิ่งขึ้น และเราก็ได้จัดเตรียมเรื่องราวใหม่ๆที่รอให้คุณค้นคว้าและไม่ควรพลาด แล้วพบกันในเร็วๆนี้ !";
  } 
  //Korean     
  else if ($language === 'ko') {
  	$langError = "현재, ELX 사이트는 시스템 업데이트로 인해 접속이 제한됩니다. \n새로운 컨텐츠와 최신 시스템으로 업그레이드된 ELX 사이트를2016년 10월 10일부터 경험해 보시기 바랍니다.";
  }
  //Japanese     
  else if ($language === 'ja') {
  	$langError = "ELXは現在、アップグレードに向けてメンテナンス中です。\n2016年10月10日には、システムが更新されて、新しいサイトをご利用いただけます。\n新しいコンテンツもロンチされる予定ですので、楽しみにお待ちください。";
  }
  //Indonesian     
  else if ($language === 'id') {
  	$langError = 'Saat ini ELX masih dalam tahap perbaikan untuk menjalankan beberapa peningkatan pada situs. Harap kembali pada 10/10/2016 (mm/dd/yyyy) untuk mencoba fitur-fitur baru dan beberapa perbaikan sistem yang menarik. Kami juga memiliki konten baru yang bisa Anda pelajari. Jangan lewatkan. Sampai jumpa!';
  }
  //Simplified Chinese     
  else if ($language === 'zh-Hans') {
  	$langError = "ELX目前处于维护模式，正在进行一系列的网站升级。2016年10月10日重新开放，欢迎届时体验令人兴奋的系统优化和全新的功能。\n我们同时也将提供全新的学习内容，精彩内容即将开启，不容错过！";
  }
  //Traditional Chinese     
  else if ($language === 'zh-Hant') {
  	$langError = 'ELX網站現正更新中，請於 10/10/2016 後再次造訪。敬請期待我們為您準備的全新學習內容，我們很快再見！';
  }
  //French
  else if ($language === 'fr') {
    $langError = 'Le site ELX est en cours de maintenance. Merci de vous reconnecter le 10/10/2016 afin de découvrir les nouvelles fonctionnalités de votre site d’apprentissage Estée Lauder.  Vous y découvrirez également beaucoup de nouveautés à ne pas manquer ! A très bientôt !';
  }
  //French(Canada)
  else if ($language === 'fr-CA') {
  	$langError = "ELX est présentement en entretien et effectue des mises à niveau pour l'amélioration de ce site. S’il-vous-plaît, revenez nous visiter le 10/10/2016 (mm/jj/aaaa) et expérimentez un système perfectionné ainsi que de nouvelles fonctionnalités. Nous aurons également du nouveau contenu à votre disposition. Ne manquez rien. Nous vous reverrons bientôt!";
  }
  //Default to English
  else {
    $langError = 'ELX is currently in maintenance mode, performing a series of upgrades for the site.  Please come back on 10/10/2016 to experience some exciting system improvements and new features. We will also have new content available for you to learn. Don’t miss out. We will see you soon!';
  }
  return $langError;
}

/**
 * Helper function that checks if logged in user belongs to the mentioned markets
 * Returns FALSE if user belongs to atleast one of the markets mentioned in the function; TRUE otherwise
 */
function _userNotBelongsToSpecificMarkets()
{
	//Load the markets - Fashion Group,South Africa,U.K.,Singapore,Canada,New Zealand,Australia,United States in that order
	$markets = array(34466,34476,34489,34498,34506,34518,34519,34520);
	$isMember = false; //Flag to check if user belongs to any of the above markets
	foreach($markets as $market)
	{
		if(og_is_member('node', $market, 'user'))
		{
			$isMember = true;
			break;
		}
	}
	return !$isMember;
}
