<?php

function elx_json_feed_shadow_request_alter(&$entity) {

// dpm ($entity);
//  $entity_array = (array) $entity;
//  dpm ($entity_array);
//
//  $size_of_entity_array = count($entity_array);
//  // dpm('number of array elements : ' . $size_of_entity_array    );
//  // load the current entity in a wrapper
//  $wrapper = entity_metadata_wrapper('node', $entity);
//  // dpm($wrapper->field_test_image->fid);
//  // given our node entity type, get all the fields for it
//  $entity_type = $entity->type;
//
//  $node_fields = field_info_instances('node', $entity_type);
//  dpm($node_fields);
//  $number_of_fields = count($node_fields);
//  // dpm($number_of_fields . ' ' . $entity_type . ' fields we found:');
//
//  $children_nodes_to_process = element_children($node_fields);
//
//  // Grab language
//  $language = $entity->path['language'];
//
//
//  for ($i=0; $i < $number_of_fields; $i++) {
//    // dpm('['. $i .']' . 'children node '. $children_nodes_to_process[$i]);
//    // dpm($children_nodes_to_process[$i]);
//    // dpm($wrapper->$children_nodes_to_process[$i]->value());
//    $info = field_info_field($children_nodes_to_process[$i]);
//
//    // BEGIN Image and Taxonomy snippet //
//    $field_name = $info['field_name'];
//    if ($info['type'] == 'image') {
//      $image_style = $node_fields[$field_name]['display']['default']['settings']['image_style'];
//
//      $fid = $entity_array[$field_name][$language][0]['fid'];
//      $file_id = file_load($fid);
//      $uri = $file_id->uri;
//
//      $image_style_path = image_style_url($image_style, $uri);
//      dpm($field_name . ': ' . $image_style_path);
//    }
//
//    if ($info['type'] == 'taxonomy_term_reference') {
//      $number_of_terms = count($entity_array[$field_name][$language]);
//      dpm($field_name);
//      for ($t=0; $t < $number_of_terms; $t++) {
//        $tids = array($entity_array[$field_name][$language][$t]['tid']);
//        $terms = taxonomy_term_load_multiple($tids);
//        foreach ($terms as $term) {
//          $name = $term->name;
//          dpm($name);
//        }
//      }
//    }
    // END Image and Taxonomy snippet //

//  }
}

