<?php
/**
 * Created by PhpStorm.
 * User: Adrienne Cabouet
 * Creates a Guest URL for each ELX User account using:
 * -field_account_name,
 * -field_door,
 * -field_country,
 * -field_region_list,
 * -field_market_name.
 * One URL for each door.
 *
 */

/**
 * Implements hook_node_presave().
 */
function elx_guest_urls_node_presave($node)
{

    //Create an empty array to store generated URLs for each door
    $URLs = array();

    //Get account name, door, country, region list, and market name fields in vars
    $acct = preg_replace('/\s+/', '', $node->title);
    $account_name = 'account=' . $acct;
    $country = 'country=' . $node->field_country['und'][0]['value'];
    $region = 'region=' . $node->field_region_list['und'][0]['value'];
    $market = 'market=' . $node->field_market_name['und'][0]['value'];

    //Get Doors (there may be multiple)
    $doors = $node->field_door['und'];

    //Loop Through Doors and create URL array for each
    if (is_array($doors)) {
        foreach ($doors as $door) {
            $door_value = 'door=' . $door['value'];
            $url_array = array(
                $account_name,
                $door_value,
                $country,
                $region,
                $market
            );
            array_push($URLs, $url_array);
        }
    }

    $i = 0;
    foreach ($URLs as $url) {
        //Example URL: http://myelx.com/#/signup?account=Acmexx&door=4&market=X&country=Y&region=Z
        $guest_url_value = 'http://myelx.com/#/signup?'; //TBD

        //Concatenate
        $amp_separated = implode('&', $url);

        //Add to guest URL value
        $guest_url_value .= $amp_separated;

        //Save each guest url in it's own field_guest_url
        $node->field_guest_url['und'][$i]['url'] = $guest_url_value;
        $i++;
    }
}


