<?php
/**
 * Add styles to H5Ps
 * 
 * @param array $styles
 *  Array of objects with properties path and version. Version is on the form
 *  ?ver=1.0.2 and is used as a cache buster
 * @param array $libraries
 *  Array of libraries indexed by the library's machineName and with an array
 *  as value. The value has the properties majorVersion and minorVersion
 * @param string $mode
 *  What mode are we in? Possible values are "editor", "div", "iframe" and "external"
 */
function elx_h5p_css_h5p_styles_alter(&$styles, $libraries, $mode) {
  //if (isset($libraries['H5P.MultiChoice']) && $libraries['H5P.MultiChoice']['majorVersion'] == '1') {
    $styles[] = (object) array(
      // Path relative to drupal root
      // 'path' => drupal_get_path('module', 'elx_h5p_css') . '/h5p-overrides.css',
      'path' => drupal_get_path('theme', 'elx_front') . '/css/h5p.css',
      // Cache buster
      'version' => '?ver=5',
    );
    //}
}
